Add PostgreSQL Support
AuraDevelopmentTeam/InvSync pull request #55
Opened 2020-10-18 13:11 UTC by HaedHutner

This should address #14 
Some notes:

* bStats 1.7's `Metrics2` class constructor is not annotated with `@Inject`, so I had to downgrade it to 1.6 in order to test.
* The comments in `gradle.properties` were written with backslashes, which is actually incorrect for `.properties` files. This PR also addresses this.

Because of the above 2 notes, this is a draft pull request.

The abstraction layer over the database connection stuff ( SqlService and the like ) was not intended for use with different sql syntaxes and implementations ( PostgreSQL's syntax is different than MySQL in many ways ), I've had to do all of this in a way which I personally don't consider optimal. If this plugin intends to support multiple databases, it should really have at least something like jOOQ or an ORM of some sort. 

⚠️ I have not done any regression testing in terms of the already-existing h2 or mysql stuff. I have only tested the new PostgreSQL functionality.

⚠️ I have also not tested this with any of the mods that are supported. Just vanilla SpongeForge.

2020-10-18 18:00 UTC, BrainStone requested changes
Thank you very much for your contribution.

However there are few issues I pointed out.  
Merge my latest commit to fix the bStats issue.

2020-10-18 18:00 UTC, BrainStone commented on src/main/java/world/jnc/invsync/config/Config.java
> +      }
Might make sense to move that to the container class.  
Not a dealbreaker if you don't.

2020-10-24 21:24 UTC, HaedHutner commented on src/main/java/world/jnc/invsync/util/database/DataSource.java
> +    if (!storageConfig.isPostgreSQL()) setActiveStr.append(" LIMIT 1");
For `UPDATE` statements specifically, Postgre does not support `LIMIT`, it's only supported for SELECT statements afaik

2020-10-24 21:28 UTC, BrainStone commented on src/main/java/world/jnc/invsync/util/database/DataSource.java
> +    if (!storageConfig.isPostgreSQL()) setActiveStr.append(" LIMIT 1");
I see. Didn't even notice that. From the looks of it it doesn't. Good catch.

2020-10-24 21:32 UTC, BrainStone commented
All looks good now.

2020-10-24 21:32 UTC, merged